// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the 'Connecting to a real Firebase project'
// guide to connect to a real Firebase project.

export const firebaseConfig = {
  "projectId": "studio-8555919986-7f9c9",
  "appId": "1:1014097693518:web:5e5ad301316269effaac1f",
  "apiKey": "AIzaSyBv8pjOZbkaO4yJateq7aZjmCFUsYwbZIs",
  "authDomain": "studio-8555919986-7f9c9.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1014097693518"
};
