// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the 'Connecting to a real Firebase project'
// guide to connect to a real Firebase project.

export const firebaseConfig = {
  apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  authDomain: "example.firebaseapp.com",
  projectId: "example",
  storageBucket: "example.appspot.com",
  messagingSenderId: "000000000000",
  appId: "1:000000000000:web:0000000000000000000000",
};
